In [1]:
import requests
import pandas as pd

1

In [3]:
base_url = "http://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD"
gdp_data = []
page = 1

while True:
    response = requests.get(base_url, params={
        "format": "json",
        "page": page
    })

    
    print(f"Status Code for Page {page}: {response.status_code}")
    
    data = response.json()
    
    if len(data) < 2:
        break

    gdp_data.extend(data[1])
    
    if page >= data[0]["pages"]:
        break
    else:
        page += 1

# Convert to DataFrame
gdp_df = pd.DataFrame(gdp_data)

# Print results
print(f"Retrieved {len(gdp_df)} rows.")
gdp_df.head()

Status Code for Page 1: 200
Status Code for Page 2: 200
Status Code for Page 3: 200
Status Code for Page 4: 200
Status Code for Page 5: 200
Status Code for Page 6: 200
Status Code for Page 7: 200
Status Code for Page 8: 200
Status Code for Page 9: 200
Status Code for Page 10: 200
Status Code for Page 11: 200
Status Code for Page 12: 200
Status Code for Page 13: 200
Status Code for Page 14: 200
Status Code for Page 15: 200
Status Code for Page 16: 200
Status Code for Page 17: 200
Status Code for Page 18: 200
Status Code for Page 19: 200
Status Code for Page 20: 200
Status Code for Page 21: 200
Status Code for Page 22: 200
Status Code for Page 23: 200
Status Code for Page 24: 200
Status Code for Page 25: 200
Status Code for Page 26: 200
Status Code for Page 27: 200
Status Code for Page 28: 200
Status Code for Page 29: 200
Status Code for Page 30: 200
Status Code for Page 31: 200
Status Code for Page 32: 200
Status Code for Page 33: 200
Status Code for Page 34: 200
Status Code for Page 35: 200
Status Code for Page 36: 200
Status Code for Page 37: 200
Status Code for Page 38: 200
Status Code for Page 39: 200
Status Code for Page 40: 200
Status Code for Page 41: 200
Status Code for Page 42: 200
Status Code for Page 43: 200
Status Code for Page 44: 200
Status Code for Page 45: 200
Status Code for Page 46: 200
Status Code for Page 47: 200
Status Code for Page 48: 200
Status Code for Page 49: 200
Status Code for Page 50: 200
Status Code for Page 51: 200
Status Code for Page 52: 200
Status Code for Page 53: 200
Status Code for Page 54: 200
Status Code for Page 55: 200
Status Code for Page 56: 200
Status Code for Page 57: 200
Status Code for Page 58: 200
Status Code for Page 59: 200
Status Code for Page 60: 200
Status Code for Page 61: 200
Status Code for Page 62: 200
Status Code for Page 63: 200
Status Code for Page 64: 200
Status Code for Page 65: 200
Status Code for Page 66: 200
Status Code for Page 67: 200
Status Code for Page 68: 200
Status Code for Page 69: 200
Status Code for Page 70: 200
Status Code for Page 71: 200
Status Code for Page 72: 200
Status Code for Page 73: 200
Status Code for Page 74: 200
Status Code for Page 75: 200
Status Code for Page 76: 200
Status Code for Page 77: 200
Status Code for Page 78: 200
Status Code for Page 79: 200
Status Code for Page 80: 200
Status Code for Page 81: 200
Status Code for Page 82: 200
Status Code for Page 83: 200
Status Code for Page 84: 200
Status Code for Page 85: 200
Status Code for Page 86: 200
Status Code for Page 87: 200
Status Code for Page 88: 200
Status Code for Page 89: 200
Status Code for Page 90: 200
Status Code for Page 91: 200
Status Code for Page 92: 200
Status Code for Page 93: 200
Status Code for Page 94: 200
Status Code for Page 95: 200
Status Code for Page 96: 200
Status Code for Page 97: 200
Status Code for Page 98: 200
Status Code for Page 99: 200
Status Code for Page 100: 200
Status Code for Page 101: 200
Status Code for Page 102: 200
Status Code for Page 103: 200
Status Code for Page 104: 200
Status Code for Page 105: 200
Status Code for Page 106: 200
Status Code for Page 107: 200
Status Code for Page 108: 200
Status Code for Page 109: 200
Status Code for Page 110: 200
Status Code for Page 111: 200
Status Code for Page 112: 200
Status Code for Page 113: 200
Status Code for Page 114: 200
Status Code for Page 115: 200
Status Code for Page 116: 200
Status Code for Page 117: 200
Status Code for Page 118: 200
Status Code for Page 119: 200
Status Code for Page 120: 200
Status Code for Page 121: 200
Status Code for Page 122: 200
Status Code for Page 123: 200
Status Code for Page 124: 200
Status Code for Page 125: 200
Status Code for Page 126: 200
Status Code for Page 127: 200
Status Code for Page 128: 200
Status Code for Page 129: 200
Status Code for Page 130: 200
Status Code for Page 131: 200
Status Code for Page 132: 200
Status Code for Page 133: 200
Status Code for Page 134: 200
Status Code for Page 135: 200
Status Code for Page 136: 200
Status Code for Page 137: 200
Status Code for Page 138: 200
Status Code for Page 139: 200
Status Code for Page 140: 200
Status Code for Page 141: 200
Status Code for Page 142: 200
Status Code for Page 143: 200
Status Code for Page 144: 200
Status Code for Page 145: 200
Status Code for Page 146: 200
Status Code for Page 147: 200
Status Code for Page 148: 200
Status Code for Page 149: 200
Status Code for Page 150: 200
Status Code for Page 151: 200
Status Code for Page 152: 200
Status Code for Page 153: 200
Status Code for Page 154: 200
Status Code for Page 155: 200
Status Code for Page 156: 200
Status Code for Page 157: 200
Status Code for Page 158: 200
Status Code for Page 159: 200
Status Code for Page 160: 200
Status Code for Page 161: 200
Status Code for Page 162: 200
Status Code for Page 163: 200
Status Code for Page 164: 200
Status Code for Page 165: 200
Status Code for Page 166: 200
Status Code for Page 167: 200
Status Code for Page 168: 200
Status Code for Page 169: 200
Status Code for Page 170: 200
Status Code for Page 171: 200
Status Code for Page 172: 200
Status Code for Page 173: 200
Status Code for Page 174: 200
Status Code for Page 175: 200
Status Code for Page 176: 200
Status Code for Page 177: 200
Status Code for Page 178: 200
Status Code for Page 179: 200
Status Code for Page 180: 200
Status Code for Page 181: 200
Status Code for Page 182: 200
Status Code for Page 183: 200
Status Code for Page 184: 200
Status Code for Page 185: 200
Status Code for Page 186: 200
Status Code for Page 187: 200
Status Code for Page 188: 200
Status Code for Page 189: 200
Status Code for Page 190: 200
Status Code for Page 191: 200
Status Code for Page 192: 200
Status Code for Page 193: 200
Status Code for Page 194: 200
Status Code for Page 195: 200
Status Code for Page 196: 200
Status Code for Page 197: 200
Status Code for Page 198: 200
Status Code for Page 199: 200
Status Code for Page 200: 200
Status Code for Page 201: 200
Status Code for Page 202: 200
Status Code for Page 203: 200
Status Code for Page 204: 200
Status Code for Page 205: 200
Status Code for Page 206: 200
Status Code for Page 207: 200
Status Code for Page 208: 200
Status Code for Page 209: 200
Status Code for Page 210: 200
Status Code for Page 211: 200
Status Code for Page 212: 200
Status Code for Page 213: 200
Status Code for Page 214: 200
Status Code for Page 215: 200
Status Code for Page 216: 200
Status Code for Page 217: 200
Status Code for Page 218: 200
Status Code for Page 219: 200
Status Code for Page 220: 200
Status Code for Page 221: 200
Status Code for Page 222: 200
Status Code for Page 223: 200
Status Code for Page 224: 200
Status Code for Page 225: 200
Status Code for Page 226: 200
Status Code for Page 227: 200
Status Code for Page 228: 200
Status Code for Page 229: 200
Status Code for Page 230: 200
Status Code for Page 231: 200
Status Code for Page 232: 200
Status Code for Page 233: 200
Status Code for Page 234: 200
Status Code for Page 235: 200
Status Code for Page 236: 200
Status Code for Page 237: 200
Status Code for Page 238: 200
Status Code for Page 239: 200
Status Code for Page 240: 200
Status Code for Page 241: 200
Status Code for Page 242: 200
Status Code for Page 243: 200
Status Code for Page 244: 200
Status Code for Page 245: 200
Status Code for Page 246: 200
Status Code for Page 247: 200
Status Code for Page 248: 200
Status Code for Page 249: 200
Status Code for Page 250: 200
Status Code for Page 251: 200
Status Code for Page 252: 200
Status Code for Page 253: 200
Status Code for Page 254: 200
Status Code for Page 255: 200
Status Code for Page 256: 200
Status Code for Page 257: 200
Status Code for Page 258: 200
Status Code for Page 259: 200
Status Code for Page 260: 200
Status Code for Page 261: 200
Status Code for Page 262: 200
Status Code for Page 263: 200
Status Code for Page 264: 200
Status Code for Page 265: 200
Status Code for Page 266: 200
Status Code for Page 267: 200
Status Code for Page 268: 200
Status Code for Page 269: 200
Status Code for Page 270: 200
Status Code for Page 271: 200
Status Code for Page 272: 200
Status Code for Page 273: 200
Status Code for Page 274: 200
Status Code for Page 275: 200
Status Code for Page 276: 200
Status Code for Page 277: 200
Status Code for Page 278: 200
Status Code for Page 279: 200
Status Code for Page 280: 200
Status Code for Page 281: 200
Status Code for Page 282: 200
Status Code for Page 283: 200
Status Code for Page 284: 200
Status Code for Page 285: 200
Status Code for Page 286: 200
Status Code for Page 287: 200
Status Code for Page 288: 200
Status Code for Page 289: 200
Status Code for Page 290: 200
Status Code for Page 291: 200
Status Code for Page 292: 200
Status Code for Page 293: 200
Status Code for Page 294: 200
Status Code for Page 295: 200
Status Code for Page 296: 200
Status Code for Page 297: 200
Status Code for Page 298: 200
Status Code for Page 299: 200
Status Code for Page 300: 200
Status Code for Page 301: 200
Status Code for Page 302: 200
Status Code for Page 303: 200
Status Code for Page 304: 200
Status Code for Page 305: 200
Status Code for Page 306: 200
Status Code for Page 307: 200
Status Code for Page 308: 200
Status Code for Page 309: 200
Status Code for Page 310: 200
Status Code for Page 311: 200
Status Code for Page 312: 200
Status Code for Page 313: 200
Status Code for Page 314: 200
Status Code for Page 315: 200
Status Code for Page 316: 200
Status Code for Page 317: 200
Status Code for Page 318: 200
Status Code for Page 319: 200
Status Code for Page 320: 200
Status Code for Page 321: 200
Status Code for Page 322: 200
Status Code for Page 323: 200
Status Code for Page 324: 200
Status Code for Page 325: 200
Status Code for Page 326: 200
Status Code for Page 327: 200
Status Code for Page 328: 200
Status Code for Page 329: 200
Status Code for Page 330: 200
Status Code for Page 331: 200
Status Code for Page 332: 200
Status Code for Page 333: 200
Status Code for Page 334: 200
Status Code for Page 335: 200
Status Code for Page 336: 200
Status Code for Page 337: 200
Status Code for Page 338: 200
Status Code for Page 339: 200
Status Code for Page 340: 200
Status Code for Page 341: 200
Status Code for Page 342: 200
Status Code for Page 343: 200
Status Code for Page 344: 200
Status Code for Page 345: 200
Status Code for Page 346: 200
Retrieved 17290 rows.

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,3968.963751,,,0
1,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,3948.142721,,,0
2,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,3974.244214,,,0
3,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,3933.580905,,,0
4,"{'id': 'NY.GDP.PCAP.PP.KD', 'value': 'GDP per ...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2020,3861.068816,,,0

2

In [4]:
base_url = "http://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN"
life_data = []
page = 1

while True:
    response = requests.get(base_url, params={
        "format": "json",
        "page": page
    })

    print(f"Status Code for Page {page}: {response.status_code}")
    
    data = response.json()
    
    if len(data) < 2:
        break

    life_data.extend(data[1])
    
    if page >= data[0]["pages"]:
        break
    else:
        page += 1

# Convert to DataFrame
life_df = pd.DataFrame(life_data)

# Show result
print(f"Retrieved {len(life_df)} rows.")
life_df.head()

Status Code for Page 1: 200
Status Code for Page 2: 200
Status Code for Page 3: 200
Status Code for Page 4: 200
Status Code for Page 5: 200
Status Code for Page 6: 200
Status Code for Page 7: 200
Status Code for Page 8: 200
Status Code for Page 9: 200
Status Code for Page 10: 200
Status Code for Page 11: 200
Status Code for Page 12: 200
Status Code for Page 13: 200
Status Code for Page 14: 200
Status Code for Page 15: 200
Status Code for Page 16: 200
Status Code for Page 17: 200
Status Code for Page 18: 200
Status Code for Page 19: 200
Status Code for Page 20: 200
Status Code for Page 21: 200
Status Code for Page 22: 200
Status Code for Page 23: 200
Status Code for Page 24: 200
Status Code for Page 25: 200
Status Code for Page 26: 200
Status Code for Page 27: 200
Status Code for Page 28: 200
Status Code for Page 29: 200
Status Code for Page 30: 200
Status Code for Page 31: 200
Status Code for Page 32: 200
Status Code for Page 33: 200
Status Code for Page 34: 200
Status Code for Page 35: 200
Status Code for Page 36: 200
Status Code for Page 37: 200
Status Code for Page 38: 200
Status Code for Page 39: 200
Status Code for Page 40: 200
Status Code for Page 41: 200
Status Code for Page 42: 200
Status Code for Page 43: 200
Status Code for Page 44: 200
Status Code for Page 45: 200
Status Code for Page 46: 200
Status Code for Page 47: 200
Status Code for Page 48: 200
Status Code for Page 49: 200
Status Code for Page 50: 200
Status Code for Page 51: 200
Status Code for Page 52: 200
Status Code for Page 53: 200
Status Code for Page 54: 200
Status Code for Page 55: 200
Status Code for Page 56: 200
Status Code for Page 57: 200
Status Code for Page 58: 200
Status Code for Page 59: 200
Status Code for Page 60: 200
Status Code for Page 61: 200
Status Code for Page 62: 200
Status Code for Page 63: 200
Status Code for Page 64: 200
Status Code for Page 65: 200
Status Code for Page 66: 200
Status Code for Page 67: 200
Status Code for Page 68: 200
Status Code for Page 69: 200
Status Code for Page 70: 200
Status Code for Page 71: 200
Status Code for Page 72: 200
Status Code for Page 73: 200
Status Code for Page 74: 200
Status Code for Page 75: 200
Status Code for Page 76: 200
Status Code for Page 77: 200
Status Code for Page 78: 200
Status Code for Page 79: 200
Status Code for Page 80: 200
Status Code for Page 81: 200
Status Code for Page 82: 200
Status Code for Page 83: 200
Status Code for Page 84: 200
Status Code for Page 85: 200
Status Code for Page 86: 200
Status Code for Page 87: 200
Status Code for Page 88: 200
Status Code for Page 89: 200
Status Code for Page 90: 200
Status Code for Page 91: 200
Status Code for Page 92: 200
Status Code for Page 93: 200
Status Code for Page 94: 200
Status Code for Page 95: 200
Status Code for Page 96: 200
Status Code for Page 97: 200
Status Code for Page 98: 200
Status Code for Page 99: 200
Status Code for Page 100: 200
Status Code for Page 101: 200
Status Code for Page 102: 200
Status Code for Page 103: 200
Status Code for Page 104: 200
Status Code for Page 105: 200
Status Code for Page 106: 200
Status Code for Page 107: 200
Status Code for Page 108: 200
Status Code for Page 109: 200
Status Code for Page 110: 200
Status Code for Page 111: 200
Status Code for Page 112: 200
Status Code for Page 113: 200
Status Code for Page 114: 200
Status Code for Page 115: 200
Status Code for Page 116: 200
Status Code for Page 117: 200
Status Code for Page 118: 200
Status Code for Page 119: 200
Status Code for Page 120: 200
Status Code for Page 121: 200
Status Code for Page 122: 200
Status Code for Page 123: 200
Status Code for Page 124: 200
Status Code for Page 125: 200
Status Code for Page 126: 200
Status Code for Page 127: 200
Status Code for Page 128: 200
Status Code for Page 129: 200
Status Code for Page 130: 200
Status Code for Page 131: 200
Status Code for Page 132: 200
Status Code for Page 133: 200
Status Code for Page 134: 200
Status Code for Page 135: 200
Status Code for Page 136: 200
Status Code for Page 137: 200
Status Code for Page 138: 200
Status Code for Page 139: 200
Status Code for Page 140: 200
Status Code for Page 141: 200
Status Code for Page 142: 200
Status Code for Page 143: 200
Status Code for Page 144: 200
Status Code for Page 145: 200
Status Code for Page 146: 200
Status Code for Page 147: 200
Status Code for Page 148: 200
Status Code for Page 149: 200
Status Code for Page 150: 200
Status Code for Page 151: 200
Status Code for Page 152: 200
Status Code for Page 153: 200
Status Code for Page 154: 200
Status Code for Page 155: 200
Status Code for Page 156: 200
Status Code for Page 157: 200
Status Code for Page 158: 200
Status Code for Page 159: 200
Status Code for Page 160: 200
Status Code for Page 161: 200
Status Code for Page 162: 200
Status Code for Page 163: 200
Status Code for Page 164: 200
Status Code for Page 165: 200
Status Code for Page 166: 200
Status Code for Page 167: 200
Status Code for Page 168: 200
Status Code for Page 169: 200
Status Code for Page 170: 200
Status Code for Page 171: 200
Status Code for Page 172: 200
Status Code for Page 173: 200
Status Code for Page 174: 200
Status Code for Page 175: 200
Status Code for Page 176: 200
Status Code for Page 177: 200
Status Code for Page 178: 200
Status Code for Page 179: 200
Status Code for Page 180: 200
Status Code for Page 181: 200
Status Code for Page 182: 200
Status Code for Page 183: 200
Status Code for Page 184: 200
Status Code for Page 185: 200
Status Code for Page 186: 200
Status Code for Page 187: 200
Status Code for Page 188: 200
Status Code for Page 189: 200
Status Code for Page 190: 200
Status Code for Page 191: 200
Status Code for Page 192: 200
Status Code for Page 193: 200
Status Code for Page 194: 200
Status Code for Page 195: 200
Status Code for Page 196: 200
Status Code for Page 197: 200
Status Code for Page 198: 200
Status Code for Page 199: 200
Status Code for Page 200: 200
Status Code for Page 201: 200
Status Code for Page 202: 200
Status Code for Page 203: 200
Status Code for Page 204: 200
Status Code for Page 205: 200
Status Code for Page 206: 200
Status Code for Page 207: 200
Status Code for Page 208: 200
Status Code for Page 209: 200
Status Code for Page 210: 200
Status Code for Page 211: 200
Status Code for Page 212: 200
Status Code for Page 213: 200
Status Code for Page 214: 200
Status Code for Page 215: 200
Status Code for Page 216: 200
Status Code for Page 217: 200
Status Code for Page 218: 200
Status Code for Page 219: 200
Status Code for Page 220: 200
Status Code for Page 221: 200
Status Code for Page 222: 200
Status Code for Page 223: 200
Status Code for Page 224: 200
Status Code for Page 225: 200
Status Code for Page 226: 200
Status Code for Page 227: 200
Status Code for Page 228: 200
Status Code for Page 229: 200
Status Code for Page 230: 200
Status Code for Page 231: 200
Status Code for Page 232: 200
Status Code for Page 233: 200
Status Code for Page 234: 200
Status Code for Page 235: 200
Status Code for Page 236: 200
Status Code for Page 237: 200
Status Code for Page 238: 200
Status Code for Page 239: 200
Status Code for Page 240: 200
Status Code for Page 241: 200
Status Code for Page 242: 200
Status Code for Page 243: 200
Status Code for Page 244: 200
Status Code for Page 245: 200
Status Code for Page 246: 200
Status Code for Page 247: 200
Status Code for Page 248: 200
Status Code for Page 249: 200
Status Code for Page 250: 200
Status Code for Page 251: 200
Status Code for Page 252: 200
Status Code for Page 253: 200
Status Code for Page 254: 200
Status Code for Page 255: 200
Status Code for Page 256: 200
Status Code for Page 257: 200
Status Code for Page 258: 200
Status Code for Page 259: 200
Status Code for Page 260: 200
Status Code for Page 261: 200
Status Code for Page 262: 200
Status Code for Page 263: 200
Status Code for Page 264: 200
Status Code for Page 265: 200
Status Code for Page 266: 200
Status Code for Page 267: 200
Status Code for Page 268: 200
Status Code for Page 269: 200
Status Code for Page 270: 200
Status Code for Page 271: 200
Status Code for Page 272: 200
Status Code for Page 273: 200
Status Code for Page 274: 200
Status Code for Page 275: 200
Status Code for Page 276: 200
Status Code for Page 277: 200
Status Code for Page 278: 200
Status Code for Page 279: 200
Status Code for Page 280: 200
Status Code for Page 281: 200
Status Code for Page 282: 200
Status Code for Page 283: 200
Status Code for Page 284: 200
Status Code for Page 285: 200
Status Code for Page 286: 200
Status Code for Page 287: 200
Status Code for Page 288: 200
Status Code for Page 289: 200
Status Code for Page 290: 200
Status Code for Page 291: 200
Status Code for Page 292: 200
Status Code for Page 293: 200
Status Code for Page 294: 200
Status Code for Page 295: 200
Status Code for Page 296: 200
Status Code for Page 297: 200
Status Code for Page 298: 200
Status Code for Page 299: 200
Status Code for Page 300: 200
Status Code for Page 301: 200
Status Code for Page 302: 200
Status Code for Page 303: 200
Status Code for Page 304: 200
Status Code for Page 305: 200
Status Code for Page 306: 200
Status Code for Page 307: 200
Status Code for Page 308: 200
Status Code for Page 309: 200
Status Code for Page 310: 200
Status Code for Page 311: 200
Status Code for Page 312: 200
Status Code for Page 313: 200
Status Code for Page 314: 200
Status Code for Page 315: 200
Status Code for Page 316: 200
Status Code for Page 317: 200
Status Code for Page 318: 200
Status Code for Page 319: 200
Status Code for Page 320: 200
Status Code for Page 321: 200
Status Code for Page 322: 200
Status Code for Page 323: 200
Status Code for Page 324: 200
Status Code for Page 325: 200
Status Code for Page 326: 200
Status Code for Page 327: 200
Status Code for Page 328: 200
Status Code for Page 329: 200
Status Code for Page 330: 200
Status Code for Page 331: 200
Status Code for Page 332: 200
Status Code for Page 333: 200
Status Code for Page 334: 200
Status Code for Page 335: 200
Status Code for Page 336: 200
Status Code for Page 337: 200
Status Code for Page 338: 200
Status Code for Page 339: 200
Status Code for Page 340: 200
Status Code for Page 341: 200
Status Code for Page 342: 200
Status Code for Page 343: 200
Status Code for Page 344: 200
Status Code for Page 345: 200
Status Code for Page 346: 200
Retrieved 17290 rows.

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2024,NaN,,,0
1,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2023,65.146291,,,0
2,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2022,64.487020,,,0
3,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2021,62.979999,,,0
4,"{'id': 'SP.DYN.LE00.IN', 'value': 'Life expect...","{'id': 'ZH', 'value': 'Africa Eastern and Sout...",AFE,2020,63.766484,,,0

3

In [5]:
gdp_df_clean = gdp_df[["country", "countryiso3code", "date", "value"]].copy()
gdp_df_clean["country"] = gdp_df_clean["country"].apply(lambda x: x["value"] if isinstance(x, dict) else None)
gdp_df_clean = gdp_df_clean.rename(columns={
    "countryiso3code": "iso_code",
    "date": "year",
    "value": "gdp_per_capita"
})

# Clean Life Expectancy data
life_df_clean = life_df[["country", "countryiso3code", "date", "value"]].copy()
life_df_clean["country"] = life_df_clean["country"].apply(lambda x: x["value"] if isinstance(x, dict) else None)
life_df_clean = life_df_clean.rename(columns={
    "countryiso3code": "iso_code",
    "date": "year",
    "value": "life_expectancy"
})

In [6]:
merged_df = pd.merge(gdp_df_clean, life_df_clean, on=["iso_code", "year", "country"], how="inner")
merged_df.head()

                       country iso_code  year  gdp_per_capita  life_expectancy
0  Africa Eastern and Southern      AFE  2024     3968.963751              NaN
1  Africa Eastern and Southern      AFE  2023     3948.142721        65.146291
2  Africa Eastern and Southern      AFE  2022     3974.244214        64.487020
3  Africa Eastern and Southern      AFE  2021     3933.580905        62.979999
4  Africa Eastern and Southern      AFE  2020     3861.068816        63.766484

4

In [7]:
country_url = "http://api.worldbank.org/v2/country"
country_data = []
page = 1

while True:
    response = requests.get(country_url, params={
        "format": "json",
        "page": page
    })
    
    data = response.json()
    
    if len(data) < 2:
        break

    country_data.extend(data[1])
    
    if page >= data[0]["pages"]:
        break
    else:
        page += 1

country_df = pd.DataFrame(country_data)

country_df_clean = country_df[[
    "id", "name", "region", "incomeLevel", "capitalCity", "iso2Code"
]].copy()

country_df_clean["region"] = country_df_clean["region"].apply(lambda x: x["value"] if isinstance(x, dict) else None)
country_df_clean["income_level"] = country_df_clean["incomeLevel"].apply(lambda x: x["value"] if isinstance(x, dict) else None)
country_df_clean = country_df_clean.rename(columns={
    "id": "iso_code",
    "name": "country_name",
    "capitalCity": "capital_city"
})

country_df_clean = country_df_clean.drop(columns=["incomeLevel"])  

country_df_clean.head()

,iso_code,country_name,region,capital_city,iso2Code,income_level
0,ABW,Aruba,Latin America & Caribbean,Oranjestad,AW,High income
1,AFE,Africa Eastern and Southern,Aggregates,,ZH,Aggregates
2,AFG,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Kabul,AF,Low income
3,AFR,Africa,Aggregates,,A9,Aggregates
4,AFW,Africa Western and Central,Aggregates,,ZI,Aggregates

In [8]:
final_df = pd.merge(merged_df, country_df_clean, on="iso_code", how="left")

final_df = final_df[final_df["region"] != "Aggregates"]

print(f"Final dataset contains {len(final_df)} rows after dropping aggregates.")
final_df.head()

Final dataset contains 14430 rows after dropping aggregates.

,country,iso_code,year,gdp_per_capita,life_expectancy,country_name,region,capital_city,iso2Code,income_level
1040,High income,,2024,58151.273199,NaN,NaN,NaN,NaN,NaN,NaN
1041,High income,,2023,57349.350089,80.150015,NaN,NaN,NaN,NaN,NaN
1042,High income,,2022,56725.566746,79.431324,NaN,NaN,NaN,NaN,NaN
1043,High income,,2021,55348.597711,78.800056,NaN,NaN,NaN,NaN,NaN
1044,High income,,2020,52198.975541,79.204352,NaN,NaN,NaN,NaN,NaN